### PR TITLE
Add new hu strings and convert to 1-character ellipsis

### PR DESCRIPTION
**Pull request by ovari**
@rhansen thank you for advising via https://github.com/rhansen/ep_adminpads2/pull/16#issuecomment-701653291

### CODE REVIEW

**Comment by ovari** [comment]
How can `hu` be added to https://github.com/rhansen/ep_adminpads2/blob/master/package.json#L4?

**Comment by rhansen** [comment]
> Can i10n please be added to:
> 
>   * https://github.com/rhansen/ep_adminpads2/blob/master/package.json#L4?

I don't think that's possible—I don't see any discussion about translations in https://docs.npmjs.com/files/package.json.

>   * https://github.com/rhansen/ep_adminpads2/blob/master/templates/admin/pads.html#L71

"Etherpad" is different in Hungarian?

>   * https://github.com/rhansen/ep_adminpads2/blob/master/templates/admin/pads.html#L74-L76

L10n of these lines (and line 71) should be done in Etherpad itself and then copied here. I'll work on that.

**Comment by ovari** [comment]
> > Can i10n please be added to:
> > 
> > * https://github.com/rhansen/ep_adminpads2/blob/master/package.json#L4?
> 
> I don't think that's possible—I don't see any discussion about translations in https://docs.npmjs.com/files/package.json.

Thank you for investigating. Should there be discussion added to https://docs.npmjs.com/files/package.json?

> 
> > * https://github.com/rhansen/ep_adminpads2/blob/master/templates/admin/pads.html#L71
> 
> "Etherpad" is different in Hungarian?

It could be the same; however, `Ether` is `Éter` (no `th` in Hungarian) and `pad` means `bench`. It if is the trademark, perhaps leave it as it is, with a description in `hu`.

> 
> > * https://github.com/rhansen/ep_adminpads2/blob/master/templates/admin/pads.html#L74-L76
> 
> L10n of these lines (and line 71) should be done in Etherpad itself and then copied here. I'll work on that.

Thank you

**Comment by rhansen** [comment]
> > > Can i10n please be added to:
> > > 
> > > * https://github.com/rhansen/ep_adminpads2/blob/master/package.json#L4?
> > 
> > I don't think that's possible—I don't see any discussion about translations in https://docs.npmjs.com/files/package.json.
> 
> Thank you for investigating. Should there be discussion added to https://docs.npmjs.com/files/package.json?

I recommend opening a new feature request at https://github.com/npm/cli/issues.

> > > * https://github.com/rhansen/ep_adminpads2/blob/master/templates/admin/pads.html#L71
> > 
> > "Etherpad" is different in Hungarian?
> 
> It could be the same; however, `Ether` is `Éter` (no `th` in Hungarian) and `pad` means `bench`. It if is the trademark, perhaps leave it as it is, with a description in `hu`.

Maybe open a new issue at https://github.com/ether/etherpad-lite/issues so that the Etherpad devs can discuss whether it makes sense to translate "Etherpad" or not. If the "Etherpad" string is localized in Etherpad itself then I'll update this plugin to localize "Etherpad" in this plugin.

**Pull request merged**
