### PR TITLE
Cherry-pick ep_adminpads3 changes

### PR DESCRIPTION
**Pull request by rhansen**
@MShultz, what do you think?

See #5.

### CODE REVIEW

**Comment by rhansen** [comment]
@MShultz: I tried these changes on my test Etherpad and the "Last edited" column is blank again.

**Comment by rhansen** [comment]
> @MShultz: I tried these changes on my test Etherpad and the "Last edited" column is blank again.

It's working in Firefox but not Chromium.  Hmm...

**Comment by MShultz** [comment]
> > @MShultz: I tried these changes on my test Etherpad and the "Last edited" column is blank again.
> 
> It's working in Firefox but not Chromium. Hmm...

@rhansen That was an issue we were running into as well. It worked on my local dev build of etherpad (tested on chrome), but pushing it up and installing it on our live version of etherpads caused the column to disappear again. Been working the last few days on trying to figure out what the issue is. I can get consoles to output for the date formatting, but haven't had the time to look into anything after that point.

**Comment by rhansen** [comment]
@MShultz: I don't want to merge this until a fix is in place for the blank "Last edited" column bug. Can you take a look?

**Comment by MShultz** [comment]
> @MShultz: I don't want to merge this until the blank "Last edited" column bug has been fixed. Can you take a look?

Looking into this tonight and this weekend. If I can't fix it with the added feature, I'll be removing the feature this weekend just so the "Last edited" column is fixed.

**Comment by MShultz** [comment]
@rhansen: Having an issue getting good debugging. The current published version of the plugin errors out with the following error whenever we go to the admin section. It's something that persists outside of these changes, so I'm trying to figure out what might have caused that. If you've got any suggestions, let me know.

image
I get this error both locally and on our production version. Running on Chrome.

**Comment by MShultz** [comment]
@rhansen I believe that this is ready to be merged.
I fixed our issues that weren't involved in this PR that I mentioned earlier and retested thoroughly. Have had success on Edge, Chrome, and FireFox both locally and on our production build. The issue was you need to clear you cache before you see the updated changes (Ctrl + F5 on most). I don't want to merge until you verify. 

I will also bump the version for these changes later to 2.1.0 since it adds a new feature. There are also some standards things I'll be updating (single ticks instead of quotes, etc.) that I'll be updating. 

This allows the date to be in US Format by using the following setting added to the settings.json file.
`
"ep_adminpads2": {
    "formatDateUS": true
  }
`
You can see that here.
image

**Comment by rhansen** [comment]
Whoops, I didn't see that you had pushed updates before I force-pushed a rebase. Would you mind re-pushing your branch (with `--force`)?

**Comment by rhansen** [comment]
Oh wait, maybe I'm misreading GitHub's UI, and you haven't pushed updates recently...

**Comment by MShultz** [comment]
I haven't pushed updates recently. Testing with what was there (probably about 45 minutes ago now, I'm hoping nothing changed) the feature works correctly. It was a caching issue we were seeing, but I'd like you to verify.  Clearing the cache shows the last edited and adds the setting.

**Comment by rhansen** [comment]
> Testing with what was there (probably about 45 minutes ago now, I'm hoping nothing changed)

I merged some cleanups into `master` and rebased this branch onto it ~15m ago. The changes I added to `master` should not affect the functionality here.

**Comment by rhansen** [comment]
Closing because #11 accomplishes the same goal in a more general way.

**Pull request closed without merging**
