### PR TITLE
en and hu translation updates

### PR DESCRIPTION
**Pull request by ovari**
"Search complete" sounds more correct
https://www.microsoft.com/en-us/language/Search?&searchTerm=Search%20complete&langID=382&Source=true&productid=undefined

If there are new strings in `en.json`, can you also please add them to the `hu.json` file (even if they are in English)?

If you could also please ping us if there are new translations it would be appreciated.

Thank you

### CODE REVIEW

**Comment by ovari** [comment]
Thank you @rhansen for all your wonderful work.

**Comment by rhansen** [comment]
> "Search complete" sounds more correct
> https://www.microsoft.com/en-us/language/Search?&searchTerm=Search%20complete&langID=382&Source=true&productid=undefined

Agreed, thank you.

> 
> If there are new strings in `en.json`, can you also please add them to the `hu.json` file (even if they are in English)?

I'm curious about this—wouldn't it be better to leave them out so that tools can automatically determine what strings have not yet been translated?

Note that I always do the following so it should always display something:

```javascript
  const msg = _('ep_adminpads2_message-id') || 'Backup text in case there is no translation';
```

> 
> If you could also please ping us if there are new translations it would be appreciated.

Will do.

> Thank you

Thank you for the translations!

**Comment by ovari** [comment]
> I'm curious about this—wouldn't it be better to leave them out so that tools can automatically determine what strings have not yet been translated?

We view the file using the GitHub web-based interface.

We copied the missing lines from `en.json` to `hu.json` and then translated them. This is:
* prone to errors; and
* if there are the same amount of lines (with removals and additions), it is likely that the changes are overlooked.

We don't have any tools except for Firefox. Will translations be shown on [TranslateWiki](https://translatewiki.net/)?

Thank you once again.

**Comment by rhansen** [comment]
> Will translations be shown on [TranslateWiki](https://translatewiki.net/)?

I'm going to wait to see what happens with ether/etherpad-lite#4317.

**Pull request merged**
