### PR TITLE
Use Date.prototype.toLocaleString() to format date

### PR DESCRIPTION
**Pull request by rhansen**
This formats the date according to the user's chosen locale.

Does this work for you @MShultz?

To try it out:
```shell
$ cd /path/to/etherpad-lite
$ npm i rhansen/ep_adminpads2#formatdate
```

### CODE REVIEW

**Comment by MShultz** [comment]
> This formats the date according to the user's chosen locale.
> 
> Does this work for you @MShultz?
> 
> To try it out:
> 
> ```shell
> $ cd /path/to/etherpad-lite
> $ npm i rhansen/ep_adminpads2#formatdate
> ```

@rhansen 
This all gets moved and put into `index.js` with the other PR, #7 
We should get that resolved and merged and then apply those changes to the newly-moved code once it's in.

**Comment by rhansen** [comment]
Does this PR avoid the need to merge PR #7?  (Does this have the result you want?)

I would rather format the date on the client, not the server, and according to the user's chosen locale.

**Comment by MShultz** [comment]
> Does this PR avoid the need to merge PR #7? (Does this have the result you want?)
> 
> I would rather format the date on the client, not the server, and format according to the locale chosen in the user's web browser.

Ran testing local and production. This works for what we're looking for and it's much cleaner and doesn't need a setting toggle. This removes our need for PR #7 which is great.

**Comment by rhansen** [comment]
> Ran testing local and production. This works for what we're looking for and it's much cleaner and doesn't need a setting toggle.

Awesome, thanks for testing.

**Pull request merged**
